Implemented functions
RyanKoech/javascript-compiler pull request #12
Opened 2023-04-24 03:10 UTC by Lynette7

2023-04-24 04:38 UTC, RyanKoech requested changes

2023-04-24 04:38 UTC, RyanKoech commented on grammer.html
> +<function-definition> ::= 'func' <identifier>? '(' (<identifier> [',' <identifier>]*)? ')' '-' '>' <expression>
Shouldn't out grammar for functions be like `func(<zero or more identifiers seperated by commas>) { <statement> }`? Also the `+ ?` and `()` are usually not found in BNFs right?

2023-04-24 16:55 UTC, RyanKoech requested changes
Finally, I think you need to implement the parser to accept function calls.

2023-04-24 16:55 UTC, RyanKoech commented on main.py
> +    def make_minus_or_arrow(self):
I don't think we'll need this anymore.

2023-04-24 16:55 UTC, RyanKoech commented on main.py
> +                tokens.append(self.make_minus_or_arrow())
I don't think we need this anymore.

2023-04-25 05:36 UTC, RyanKoech approved these changes

2023-04-25 06:29 UTC, m-vely approved these changes

2023-04-25 06:50 UTC, MainaKarl approved these changes

2023-04-25 07:33 UTC, merged